name: Deploy to Cloudflare
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build and deploy site
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: swift run
    - name: Install Wrangler
      run: npm i @cloudflare/wrangler -g
    - name: Deploy
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      run: cd Cloudflare && wrangler publish --env production